### ISSUE TITLE
ftp_close(): 114 is not a valid FTP Buffer resource

### ISSUE THREAD

**Issue by wingsryder** [yii2mod/yii2-ftp#8]
**ERROR:**

PHP Warning – yii\base\ErrorException

ftp_close(): 114 is not a valid FTP Buffer resource

----

```
6. in C:\xampp\htdocs\myapp\vendor\yii2mod\yii2-ftp\FtpClient.php at line 76 –
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method yii2mod\ftp\FtpWrapper::close() does not exist' in C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php:199
Stack trace:
#0 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php(199): ReflectionMethod->__construct('yii2mod\\ftp\\Ftp...', 'close')
#1 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('yii2mod\\ftp\\Ftp...')
#2 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php(249): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php(308): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#4 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\views\errorHandler\exception.php(385): yii\web\ErrorHandler->renderCallStackItem('C:\\xampp\\htdocs...', 76, 'yii2mod\\ftp\\Ftp...', 'close', Array, 6)
#5 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php(249): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\ErrorHandler.php(114): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#7 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#8 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#9 {main}
Previous exception:
exception 'yii\base\ErrorException' with message 'ftp_close(): 114 is not a valid FTP Buffer resource' in C:\xampp\htdocs\myapp\vendor\yii2mod\yii2-ftp\FtpWrapper.php:79
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'ftp_close(): 11...', 'C:\\xampp\\htdocs...', 79, Array)
#1 [internal function]: ftp_close(Resource id #114)
#2 C:\xampp\htdocs\myapp\vendor\yii2mod\yii2-ftp\FtpWrapper.php(79): call_user_func_array('ftp_close', Array)
#3 C:\xampp\htdocs\myapp\vendor\yii2mod\yii2-ftp\FtpClient.php(76): yii2mod\ftp\FtpWrapper->__call('close', Array)
#4 C:\xampp\htdocs\myapp\vendor\yii2mod\yii2-ftp\FtpClient.php(76): yii2mod\ftp\FtpWrapper->close()
#5 [internal function]: yii2mod\ftp\FtpClient->__destruct()
#6 [internal function]: app\modules\inventory\controllers\SyndicationController->actionProcess()
#7 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('process', Array)
#10 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('inventory/syndi...', Array)
#11 C:\xampp\htdocs\myapp\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 C:\xampp\htdocs\myapp\web\index.php(13): yii\base\Application->run()
#13 {main}

```

**My Code:**

       $ftp = new \yii2mod\ftp\FtpClient(); 
        $host = '192.168.1.70';
        $login = 'xxxxxx';
        $password = 'xxxxx'; 
        $ftp->connect($host);
        $ftp->login($login, $password);
        $source_directory = Yii::$app->basePath . '/web/uploads/folder1/';
        $file = 'sample.csv';
        $target_directory = Yii::$app->basePath ."/web/uploads/test/";
        $ftp->put($file , $source_directory.$file,FTP_BINARY);
        $ftp->close();

**Comment by wingsryder** [comment]
if also you can tell what function or variable we can add remote folder name.
 $ftp->put($remote_path . $file , $local_path,FTP_BINARY);
this  give error .  local path can take full path , where the remote path work only if we give filename. It crash if we set remote folder  eg: /web/uploads/test

**Comment by morontt** [comment]
@wingsryder Please check target directory. Maybe you using incorrect path? Try to write a file by another client (for example browser, FileZilla, TotalCommander, etc.)

![It is working](https://morontt.info/uploads/blog/2017/02/yii2mod_ftp.png)

**Comment by wingsryder** [comment]
if I comment the code   //$ftp->close();   system upload file properly.  Even If I enable this code, system throw error but file are uploading well.

**Comment by exru** [comment]
the same problem
